### ISSUE TITLE
Creación de página Log In

### ISSUE THREAD

**Issue by carlosgortiz** [carlosgortiz/stock-taking-web-app#3]
Se tiene que generar la página para el Log In de la aplicación web Consulta de Inventario. 

* Debe de contener una entrada (cuadro de entrada) para el usuario y uno propio para la contraseña. 
* De de tener un botón de Log In para validar que las credenciales pertenezcan a un usuario registrado y permisos de entrada.

**Comment by dorecio** [comment]
Se completa issue#3
